language: node_js
node_js:
- '6.10'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAILJJKURL5KF2EKTA
  - AWS_DEFAULT_REGION=us-west-2
  - secure: ZzItUNa35VZSjl0n6Ur2qJ0XdGI3a5r3S3s8hVoWX3KUhqGJHwGgqDT3yhM6yfjKce4Q775F8iOB6uSpl4H+ZdHUYd7SF+cfovMoOQotqSfBobclwtxQJ59Jo0i+3EPoHgCmjme1NPBFonOMDE03iwPUZ/uzQUmsNdoGzN5DTyul4pn1TQwb7WIiR1Pzz2gXjnFIXVOwu5jNFh9hQyTQQEqJtQKXXBjwya/lzO0gZPo4nHJlyB9g7Sa4wTfl6fNvW1cMHe4apz1WlxbqfymZTfWADsOXdYQDmFraeB9IPYOR25mb8DflrFjwKf7elYB2kYTmiRAMCBtZmF0Qy0HxcmfT1FJxmh/+6D3MXtijioV6vu2jHTwlQol2YhHdfY+gCuVUb2u9AWh/wSSdDpyt0X5mXUF/QBLz3v38Ip/xOEZmQQLQTWsZYj91wqHvmlYigSV+rq7YCyyqXdYx1glXLayDMUef82aO8+EpQXCd2KMOUR6GRL4N8KqB00Zs6nwNuQAYAxXGPGB+A9AtNSPo80XpN2iFYz5prcxW2LF0xiQX1GlggInw9oQ3JMv24s9l3kPcCxHw4it+1oDysPGIZkaY7Gse6nbLVwgfYnfr19+66mAedlz5gZfWv1VknXe7DiF/h9YkedOp127mX6Y2EmxYXhp+jW+lWDqXZdf3WfQ=
branches:
  only:
  - master
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script: make build
