language: node_js
node_js:
- '6.10'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJGCAHDHKA75MOCYA
  - AWS_DEFAULT_REGION=us-west-2
  - secure: CmpH3FaBMkbzECdj0TI4NJ5RBxJzUaf67AwXyYq0y877IGGbsfcAhQ5L0XNN6AklIbkj8tPo0EOjCJDbWmOy5RXIsb+02x7EwNaeqdIzEtR1/Fv4Zqjd9moTRxm1WxWNygRephYJH08MaIe1+eu4kOIGGMV7n1SCW3XTwK3b4WPioqz21uOpact1BPy5h2oirrWAZ2az9JxzY+npAUm6cETY93OA4rGhf0UBC8e4tjX8Cv9IH/WO5bqw8EjOO+qhhfIMHmRTC5xkj+0XRARP5HfqzQwIlbhkl/nfH1AB39dCqyA/bUhD+81JlOHuVwjQlV+qxeD7Qc+Q0/aAWlGDXSKeII/LDFqUg+SpHPBM4mhq+wjbktqkkrFNomfbfLfsDdffl8mbrDwKDeuK3hke3HkFF/ri4Dq5tjM3B6IE2qCDynC2kEd27KQvVRjuMD6rYI0zGypSRZdFxAKxvJANXK0Ctw11aWhcHME7FNOi5rKu0ro3cZebth0MAFJwZDzp5zsEWlGWLxmpZ35eWM+8XM35tphPNxjIS57IFMYkHX6lbTTLDRqkIrbVTty1YqGzXhWe/0ZeogFrG0kS5CnaFIqddSzwM7MWE+mC4bh/dBBheEzLkjoi88mGIQI/6a6D+h2UALGSIipWiZevWHBbB1wMt83GMycd/kf0yftlgnE=
branches:
  only:
  - master
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script: make build
dd:
  secure: UtbLdH1+p2WL40etG9qR8xnaZYDQxgbiiAOvYsQ8pyg6hlgXs8d3MIXSfrjUnEOR1v7wU5sJ3ehGLyBkN33JwT3NW4m6eggu/CFSD02hEZJk21NAB+XWLh+QThUBuYeibvbx4TxgaEBzHkn57GQFNsXn628QZt65N1/dC3F3G6YfGVncMs6GzS4MyL+XuBPTA7vKz8kfh80iNAl5l/sRcc5vmEE89YOt0FwDU2TpZNxZJNkWS0iwcd+Y5JxWC/jEuPBDgV2InCXCklJKWP8x9RpZFBMXwfekuEKQ9RmrQroAoHR6jq3kAZxUssapQ+TydKLzOMlllnTCfAb0WlU1qn7sWXWKpqazyiZANwACFq7jN5Lck0fmo3aUrvqx3cU/PZ3AnbfznEcwDDSdWtfY7baetCo+2faokUadU5bwQYtYnxigA5LfxibzNzM7zl+fQsFp9h9TSTFEHghwl2EAw1nmWB4NLl/ynbwCIq1Eq7JyxtCLYntHSHDbn26ZaZakzKAUSjk91Z9e0K2oGRrJbTG2KvqXc1r7aRfPZujY7yn2F8I9kyXaA+wvQV7oLfZmS9yXlmI0gRfh/TQAUGEsSXGG24XcTM9ysEg0/BAN9LfJtJBA3Bsrgiu/2Eoj3njSDRt1Tiiv6NSBcjpLfShAXkQCqvukRuTfEnmoMdT/3ns=
