language: node_js
node_js:
- '6.10'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAILJJKURL5KF2EKTA
  - AWS_DEFAULT_REGION=us-west-2
  - secure: A9LtI/8UXdK3jCeVyoSkDfyVWwLTtXmNqgUmUC1aOekDArSceaw2f4NKn5O7XVpi8fgXVs+z+7nQa8L3eMRpBHdYLz6raSAMAIh/gU5PaMFYJk8NUgutrnSmUCG1jRDjM4y/ySHURD60EsGT2t6FhOp/Ct28I4T3bNPSLtRLNMSWp5vAkwuHUTRWrIT4THwHZXJQNe0+932TxR+Olcip1JRO0sL+KucPDZQtXeOIA9Ky8Pfx8DNfOPY3RFHLCgW5PXI8c+C3lI3g0H+khRABIk9MjB4hRFYxGQA5gQgMjnDwm2yDTbXvZ/vkzRcnk7yxNU6NfWF6B09Bf2xcdfxndB3e4ir0RZUONaRfAvurBK1KqUD7ViKUY04O6xcYlzlIOHn08W6UfosP8+eAiW/WtrP/vNS6n7Ntldn0nuPqxO/senfIQUFVkkAyJGAJ9/ux/bb2L0tZxqg+PXnMJhFyUxLAfhS8kh1jXsOXTMmakg0UY+Wy+H5addyWPCOZBki6J9iKRkaTZfiBWMq4AUI1waFyctbvwTla2yPEvtltXWxPwm5Tm3yPf4PhXjcj7vF5tbhjcajqucJxGk+lwFtJC5gNN94kBTzxcZYPAdYWpBJLfB5jFAI4Prjng6IDA4D+MVhCe+iJfEZElPJheeg5ONzmYdMhunSGI4gO0goMhAY=
branches:
  only:
  - master
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script: make build
notifications:
  slack:
    secure: XgUpZpqUpHXnMWr27tD0cuQGUFt54cnK+nknr89o5A3xYY9GPuH/Bl2E0iJxIdjTd74vBHtZVuMiN1EEf8GuXcAV1JmGNJ4QSTLbz5ByMZBgI7PKNpFeU3PpsLqffnPAKPekvZH/hHKea/ib4mNKAGdg3Zf0FINvejUcB2/yr9X+xIZ8QPe/3u1TQ/Tr6m9Shi9jBceSh9ZjqWf0Nups2CqgT8HpNJrU5drHgfYsYpk9AjfOndxB37mmMDV0E2YFl6eckxH/HSNgIVTD2FrMBMN43VzQyfXJGFg2NtJqHuCpUhuiHxsOPOInHzv+ihnLDlGGJcsuf0k5TCBLhpkfJg7t89Kb5kgYcD6iAnv17f4SJPTMK+9nmax6k1np46ZwX5YddfRgQY1FHe+r6fwWER9yRjRotGDm73qbNlM7DyxH/IK02T9RFAC5lnpzZ8UzfWyCgsOxRyPBAyZdToYzbK1LBrtR6Ndx67fhqFH8BE0KJlvARcrJlgR0zJyX6cuZLHaoIdVmGcVFf2Sx9T26YdYLSWdRsO0WZyEVdSYEHMo63uTcT5d9oClL8vIqaTxOoSZ7eIOCiMloVIeM5UJSH2b7Q9G/i5EBTScIUQ5GjRLBxjLTV/LjO22VE3DrBoSOkRU28/e8v2AX9MZfFYB6tiwuwktzaabdGVhXrNj/C4g=
