language: node_js
node_js:
- '6.10'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJGCAHDHKA75MOCYA
  - AWS_DEFAULT_REGION=us-west-2
  - secure: "aRtLL5JFp0FLXJjJk4dy2o/lkLd0o0hErv/H7Q6wjeMdzs/QbSK6wac/CQI9yKJHiCBJxaRpn8uIx7EPKpGoo/lDeeM5hdpTkxIQjbuf3O18SNjKrLGijHMIFPIwBZ3Lwo6q+BHZICcaVao5CKvR4ZpRILkpY/N+91HwudDpGQXdm0o5KlixXjkYcpYr8wWncRwIseV2TXSHeDQ8s
  gVOyVgEy0vjn9zq9OWw4IRgwmgnAsSJbYA9TDbmkp4mX2NpAvLrwRKNnyGt93h7eVDhnwoDzh8hymMUTU3QwNS6y07kvYA6xfQ879ejrglNQdCAJIn9nUZE0ybTTPCncTKCCI4PzhZDtpKxYbVbNI2dSABUE+2u/daDzdjIJ7Qhi9bmX5aBHdcaMp1QXRB7ib2EGydUjDBqIpwAx1KhtYAJCF+NH
  U8uupX8rCyUrrlp3nTXxBxe4kPXjzB6H1JGSZ7DCsTmhit2J4YZZby0UUa6llHmVbMpZe41S0wNUDs69zi1fLbbwCPRqAqEaP4dTC+1Z0XSzaAXEnZ/J7uShGCTcd6M2hX7hGmt8Q4sejpbQFKzyYoY7YSpueifQJnFHATdwEHqaT0P/EQzUVHpQ7Ik+oEvsSaDo5Vu+CqBvo0MjtChOhS2dpF4A
  oSZlC/4k/SMJKzvIiPnCJoijH3b7txJwC0="

branches:
  only:
  - master
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script: make build
dd:
  secure: UtbLdH1+p2WL40etG9qR8xnaZYDQxgbiiAOvYsQ8pyg6hlgXs8d3MIXSfrjUnEOR1v7wU5sJ3ehGLyBkN33JwT3NW4m6eggu/CFSD02hEZJk21NAB+XWLh+QThUBuYeibvbx4TxgaEBzHkn57GQFNsXn628QZt65N1/dC3F3G6YfGVncMs6GzS4MyL+XuBPTA7vKz8kfh80iNAl5l/sRcc5vmEE89YOt0FwDU2TpZNxZJNkWS0iwcd+Y5JxWC/jEuPBDgV2InCXCklJKWP8x9RpZFBMXwfekuEKQ9RmrQroAoHR6jq3kAZxUssapQ+TydKLzOMlllnTCfAb0WlU1qn7sWXWKpqazyiZANwACFq7jN5Lck0fmo3aUrvqx3cU/PZ3AnbfznEcwDDSdWtfY7baetCo+2faokUadU5bwQYtYnxigA5LfxibzNzM7zl+fQsFp9h9TSTFEHghwl2EAw1nmWB4NLl/ynbwCIq1Eq7JyxtCLYntHSHDbn26ZaZakzKAUSjk91Z9e0K2oGRrJbTG2KvqXc1r7aRfPZujY7yn2F8I9kyXaA+wvQV7oLfZmS9yXlmI0gRfh/TQAUGEsSXGG24XcTM9ysEg0/BAN9LfJtJBA3Bsrgiu/2Eoj3njSDRt1Tiiv6NSBcjpLfShAXkQCqvukRuTfEnmoMdT/3ns=
