language: node_js
node_js:
- '6.10'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJGCAHDHKA75MOCYA
  - AWS_DEFAULT_REGION=us-west-2
  - secure: LtkL1CJkQ0DLuQDxAnf3CLmUV29+f1x+Vvk2gfbDnyXYK4zKI09KoeoZTEv+VZPTGhMmoXCO6UngvF8asRpIKpcQLqlGTPfmX4dtZRHa+pJRHUK9WTpMUGizGo//7/eWnUS2N5DGqeM/fe+k4YHzcH4P7ZzHQfMrAa9Si1DrJw2uDxDRAvW5uca0p3P5BDom1eTAYVXWrLZF8VOW3SWz41SSHMZ+ZlyVbpFvq9rL2x2xn5LTJVNWFAM5QkcY85f2IxMaobyBzBcsdOdkx5zOVUKczK4O6c5yf74lBWPiyIDfPolK10G6gVzw050SVXHQjMbdSO417KlyqAGkoWC5jsekoBivU7Y5TkOEfiqH7Rf+drpLxiwUvh7Y1EgR61ZKwvllq/tHpMV3wrRRrduJyIlprEkdjRpKUA9uxrOxKAvoCMJjqG/fx0g6L0XcZ2mUO9zND6j4kVNrKMkc+AVvlIxXYBaLn52dmDJyeozeeVTVzJ6OeouckwpnDw6Trbd6ztN0othtQHaB79n8/prEKcxfXXh3oP1TqrqITqeh2v/BkRu26A1MRIYONa96UcAZx8odK6I1oBWbY3XOdVv3sPOqZkB9+9mxgqbxXeZIZJ849wJ3PBdeztGwdnEak/0qQndTKPlATiquOZCRgya6hne64HzPP2GPkApvognrZyM=
branches:
  only:
  - master
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script: make build
